ci: Switch to GitHub Action (wip)
Use ubuntu-18.04 to try to fix build errors

Error:

  time.c:88:28: error: conflicting types for ‘gettimeofday’
     88 | int RETRACE_IMPLEMENTATION(gettimeofday)(struct timeval *tv, struct timezone *tz)
        |                            ^~~~~~~~~~~~
  common.h:170:39: note: in definition of macro ‘RETRACE_IMPLEMENTATION’
    170 | #define RETRACE_IMPLEMENTATION(func) (func)
        |                                       ^~~~
  In file included from common.h:9,
                   from time.c:26:
  /usr/include/x86_64-linux-gnu/sys/time.h:66:12: note: previous declaration of ‘gettimeofday’ was here
     66 | extern int gettimeofday (struct timeval *__restrict __tv,
        |            ^~~~~~~~~~~~